name: 'Deploy Azure SQL Database schema'

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  deploy_database_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Deploy Database Job
    steps:
      # Update to the latest version of checkout action
      - uses: actions/checkout@v3
      
      # Update to the latest version of Azure SQL action
      - uses: Azure/sql-action@v2
        with:
          connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
          # Use 'path' instead of 'dacpac-package'
          path: './database/dacpac/bus-db.dacpac'
          action: 'Publish'
